### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Mangeshrex**
added fetch link as per the pattern + the image

### CODE REVIEW

**Comment by TorchedSammy** [comment]
i meant the commit message...
why did you even remove the spaces at the end of entries either? the enitre `N` section is on 1 line now.
also dont open another pr to fix the changes

**Comment by Mangeshrex** [comment]
Umm :( sorry I didn't get that day so I just saw the pattern and made the changes. Ok can you pls do those changes yourself? Cause my laptops motherboard is damaged.

**Comment by TorchedSammy** [comment]
ill add it myself

**Comment by Mangeshrex** [comment]
Thanks

**Pull request closed without merging**
